name: CI/CD 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up CML
        uses: iterative/setup-cml@v2
    
      - name: Register ZenML Experiment Tracker
        run: zenml experiment-tracker register mlflow_tracker --flavor=mlflow

      - name: Register ZenML Model Deployer
        run: zenml model-deployer register mlflow --flavor=mlflow

      - name: Register ZenML Stack
        run: zenml stack register local-mlflow-stack-new -a default -o default -d mlflow -e mlflow_tracker --set

      - name: Set Zenml Stack
        run: zenml stack set local-mlflow-stack-new

      - name: Run CI/CD script with Secrets
        env:
            MONGO_URI: ${{ secrets.MONGO_URI }}  # Access MONGO_URI from GitHub Secrets
            API_URI: ${{ secrets.API_URI }}      # Access API_URI from GitHub Secrets
        run: python run_ci_cd.py

      - name: Publish CML Report
        run: |
          cml-publish report.txt --md > report.md

